### ISSUE TITLE
Missing v1 tag

### ISSUE THREAD

**Issue by lovasoa** [dokku/github-action#12]
Hello,
  The dokku docs mention the following github workflow file:

```yml
---
name: 'deploy'

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@v1 # <-- problem
        with:
          git_remote_url: 'ssh://dokku@dokku.me:22/appname'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

source: https://dokku.com/docs/deployment/continuous-integration/github-actions/

However, this does not work, because there is no `v1` tag in this repo. 
It would be great to create a v1 tag and point it (currently) to v1.0.2.
