### ISSUE TITLE
Error loading key "/root/.ssh/id_rsa": error in libcrypto

### ISSUE THREAD

**Issue by flowck** [dokku/github-action#51]
Hello,
I am having the following issue while deploying an app using `dokku/github-action@master`. I suppose the error might be related to the private key.

I appreciate any help. Thx

## Pipeline config

```yml
- name: Deploy
  uses: dokku/github-action@master
  with:
      branch: main
      ssh_host_key: ${{ secrets.SSH_HOST_KEY }}
      ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_remote_url: 'ssh://dokku@x.x.x.x/app-name'
```

## Result
![Screenshot_2023-05-09_at_15_23_47](https://github.com/dokku/github-action/assets/1679333/a1880023-0481-4597-8694-9249602b6db8)
