### ISSUE TITLE
fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by danjac** [dokku/github-action#58]
I have the following action:

```yaml
name: deploy:dokku

on:
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Cloning repo
              uses: actions/checkout@v3.5.3
              with:
                  fetch-depth: 0

            - name: Deploy to Dokku
              uses: vitalyliber/dokku-github-action@v7.1
              with:
                  branch: main
                  git_remote_url: "ssh://dokku@radiofeed.app:22/radiofeed"
                  ssh_private_key: ${{ secrets.DOKKU_SSH_PRIVATE_KEY }}
```

This results in this error:

```
Warning: Unexpected input(s) 'branch', 'git_remote_url', 'ssh_private_key', valid inputs are ['entryPoint', 'args', 'private_key', 'public_key']
Run vitalyliber/dokku-github-action@v7.1
/usr/bin/docker run --name c9a4a5efe2434e44a4444da4a3fe102f2bc9b4_4c75f4 --label c9a4a5 --workdir /github/workspace --rm -e "INPUT_BRANCH" -e "INPUT_GIT_REMOTE_URL" -e "INPUT_SSH_PRIVATE_KEY" -e "INPUT_PRIVATE_KEY" -e "INPUT_PUBLIC_KEY" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/radiofeed-app/radiofeed-app":"/github/workspace" c9a4a5:efe2434e44a4444da4a3fe102f2bc9b4
Setting up SSH directory
Saving SSH key
fatal: detected dubious ownership in repository at '/github/workspace'
Detect the project default branch: master or main
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace
ssh: Could not resolve hostname : Name or service not known
Default is master
Disabling host key checking
Adding repository directory to the git global config as a safe directory
The deploy is starting
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Manual dokku deployments and commands through SSH all work fine.

I'm wondering if the issue is with `Unexpected input(s) 'branch', 'git_remote_url', 'ssh_private_key',` so it's not reading those values?
