### ISSUE TITLE
Post review app destroy hook

### ISSUE THREAD

**Issue by mikejpeters** [dokku/github-action#93]
I would like to run extra commands (i.e. to destroy the mysql database) after my review app is destroyed.

I noticed at [dokku/ci-docker-image](https://github.com/dokku/ci-docker-image?tab=readme-ov-file#hooks) it lists a `bin/ci-post-review-app-destroy` hook, but when I add the hook it doesn't seem to get called.

I'm assuming this isn't a bug, because the README here only mention `bin/ci-pre-deploy`, but I was just hoping to get a better understanding in case there is a way to do this that I'm missing.  Thanks!

I'm using `dokku/github-action@v1.6.1` and have dokku version 0.35.11 on my server

**Comment by josegonzalez** [comment]
Can you paste your workflow file and the logs from the app destroy? This should be working fine, as long as the script exists in the app root: https://github.com/dokku/ci-docker-image/blob/main/bin/dokku-deploy#L63-L70

**Comment by mikejpeters** [comment]
Aaah I think the problem is that I forgot to checkout the code in the destroy job, so of course the hook file doesn't exist:

```yml
jobs:
  destroy:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'

    steps:
      # Need to add a step that uses actions/checkout here!
      - uses: dokku/github-action@v1.6.1
        with:
          command: review-apps:destroy
```

Thanks for your response, and sorry for the bother!
