### ISSUE TITLE
review_apps: Pushing last commit of a PR to update the reviewing app

### ISSUE THREAD

**Issue by mattions** [dokku/github-action#94]
Hi!

I'm trying to understand how to use the review_apps command in the proper way.

According to the docs on the https://github.com/marketplace/actions/dokku, the review apps should either create or push the last commit. Here is the excerpt (bold is mine).

> `review-apps:create`: Used to create a review app - via `dokku apps:clone` - based on the appname configured in the `git_remote_url`. If the review app already exists, this action will not recreate the app. **In both cases, the current commit will be pushed to the review app.**

When I look at the example script https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml 
It seems it is set to run only when the PR is open the first time: https://github.com/dokku/github-action/blob/40a653ce860fc6947afe0325c6ecc283979c13b3/example-workflows/review-app.yaml#L13C5-L13C79

```
# only run when a pull request is opened
    if: github.event_name == 'pull_request' && github.event.action == 'opened'
```

So what I do not understand is how to obtain the behavior written in the docs:
```
if new PR:
   clone_app
elseif PR == synchronize:
   push latest commit and redeploy
else if PR == closed:
  destroy_app
```

The problem is that when I push a new commit to an existing PR, the job is simply skipped due to the if above.
If I try to make it run on the `synchronized` event, I get the error of the like: "Name taken, the app already exists"

Can you give me a hint?
Thanks!

**Comment by mattions** [comment]
I've looked at the output form Dokku and it seems that I can't get it deployed at all, because it's not pushing to the master:main branch:

```
Ensuring review app 'review-ippocra-staging-231' exists
-----> Cloning ippocra to review-ippocra-staging-231
-----> Creating `...
-----> Creating new app virtual host file...
-----> Skipping DOKKU_PROXY_SSL_PORT, it is not set in the environment

Pushing to Dokku Host
remote: -----> WARNING: deploy did not complete, you must push to main.        
remote: -----> for example, try 'git push <dokku> master:main'        
To ssh://app.ippocra.com:22/review-ippocra-staging-231
 * [new branch]      3666694ff5b37bc4ec82c04e053869714b4abb[28](https://github.com/ippocra/ippocra-web/actions/runs/12182276512/job/33980890529#step:4:29) -> master
```
but this is supposed to push to a branch called `review-ippocra-staging-231` ?
Did I configure something wrong?

**Comment by josegonzalez** [comment]
Can you post your entire workflow here?

**Comment by mattions** [comment]
Yes.

It's a Cut and Paste of the example one: https://github.com/dokku/github-action/blob/master/example-workflows/review-app.yaml 
with just the `git_remote_url` pointing to my dokku

```
---
    name: 'deploy'
    
    # yamllint disable-line rule:truthy
    on:
      # onl run this workflow on pull request events
      pull_request
    
    jobs:
      review_app:
        runs-on: ubuntu-latest
        # only run when a pull request is opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        steps:
          - name: Cloning repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Push to dokku
            uses: dokku/github-action@master
            with:
              # create a review app
              command: review-apps:create
              git_remote_url: 'ssh://dokku@app.ippocra.com:22/ippocra'
              # specify a name for the review app
              review_app_name: review-ippocra-staging-${{ github.event.pull_request.number }}
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      destroy_review_app:
        runs-on: ubuntu-latest
        # only run when a pull request is closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        steps:
          - name: Destroy the review app
            uses: dokku/github-action@master
            with:
              # destroy a review app
              command: review-apps:destroy
              git_remote_url: 'ssh://dokku@app.ippocra.com:22/ippocra'
              # specify a name for the review app
              review_app_name: review-appname-${{ github.event.pull_request.number }}
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

```

**Comment by josegonzalez** [comment]
Can you show the entire output of the deploy?

**Comment by mattions** [comment]
@josegonzalez was the above what you were looking for?

**Comment by josegonzalez** [comment]
For the app being cloned and the new app, can you show the output of:

```shell
dokku git:report $APP
```

**Comment by mattions** [comment]
```
mattions@battlecruiser:~$ dokku git:report ippocra
=====> ippocra git information
       Git deploy branch:             main
       Git global deploy branch:      master
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       HEAD
       Git source image:
       Git last updated at:           1733835489
```


I've now run the command:

`dokku git:set --global deploy-branch main`

and now the report looks like:
```
mattions@battlecruiser:~$ dokku git:report ippocra
=====> ippocra git information
       Git deploy branch:             main
       Git global deploy branch:      main
       Git keep git dir:              false
       Git rev env var:               GIT_REV
       Git sha:                       HEAD
       Git source image:
       Git last updated at:           1733835489
```

however, every time there is a new push on the PR, the review app workflow just gets skipped.
Is that supposed to run only on the first PR opening?

**Comment by josegonzalez** [comment]
The condition there is:

```
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
```

Seems like maybe that should be:

```
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
```

Though not sure what the list of actions are so maybe it should be more comprehensive.

This is what I do for nginx:

- create pr/updates: https://github.com/dokku/heroku-buildpack-nginx/blob/master/.github/workflows/review-app.yml
- on pr close/merge: https://github.com/dokku/heroku-buildpack-nginx/blob/master/.github/workflows/review-app-cleanup.yml

**Comment by mattions** [comment]
@josegonzalez managed to get it working! Thanks for the help.

This is what worked out in the end.
Leaving here in case it's useful to someone else:

```
    jobs:
      review_app:
        runs-on: ubuntu-latest
        # only run when a pull request is opened
        if: github.event_name == 'pull_request' && github.event.action != 'closed'
        steps:
          - name: Cloning repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Push to dokku
            uses: dokku/github-action@master
            with:
              # create a review app
              command: review-apps:create
              git_remote_url: 'ssh://dokku@app.ippocra.com:22/ippocra'
              # specify `--force` as a flag for git pushes
              git_push_flags: '--force'
              branch: main
              # specify a name for the review app
              review_app_name: review-ippocra-staging-${{ github.event.pull_request.number }}
              ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
```

I'm gonna close the issue. Thanks again!
